### PR TITLE
add delay as syntax-sugar for Future.delayed

### PR DESCRIPTION
**Pull request by jodinathan**

### CODE REVIEW

**Comment by felixblaschke** [comment]
Hi Jonathan,

thank you for your contribution. I think it's a very useful extension. 👍 

Can you please provide a unit test for that function, like

```pseudocode
var n = 0;
100.milliseconds.delay.then(() => n=1}
assert(n, 0)
await 120ms;
assert(n, 1)
```
or any other working example using a delay 😄

**Comment by jodinathan** [comment]
@felixblaschke I have added the test

**Review by felixblaschke — APPROVED** [review]

**Comment by felixblaschke** [comment]
Thank you. It looks good 👍

**Comment by felixblaschke** [comment]
I updated your tests cause they had linter issue.

Changes went live with supercharged_dart 1.2.0 and supercharged 1.10.0

**Pull request merged**
