### PR TITLE
added eight char hex string color paser

### PR DESCRIPTION
**Pull request by rurico**
hi, added a color parse to handle eight chars hex string

### CODE REVIEW

**Comment by felixblaschke** [comment]
Hi! Thank you for your contribution to the project.

I see some flaws in the API when we accept 8 char hex string. Here is my observation:

- You used "OORRGGBB" in the documentation. I'll guess "O" for "Opacity" which is commonly used as a decimal ranging from 0.0 to 1.0.
- More commonly "A" for "Alpha" is the correct term when using hexadecimal numbers.
- There exists multiple representation, RGBA as well ARGB, differing on the position of the alpha value.
-  https://en.wikipedia.org/wiki/RGBA_color_model
- RGBA seems to be the most common representation (Wikpedia article, Google search results number) while Dart itself implements Colors in the ARGB byte format `Color(0xFF666666)` (fully opaque gray)

For the library I focus on developer intuitivity and code readability. Therefor I prefer using either RGBA **OR** to not implement 8 char parsing. If we take the last option I'll prefer using `"#666666".toColor().withAlpha(0xFF)` or `"#666666".toColor().withOpacity(1.0)`.

What's your opinion on that?

**Comment by rurico** [comment]
Firstly, Thanks for you nice project, In my current project, used 8 characters to dynamically generate colors. add color depth to express rich colors.
The `HTML` uses the `#66666699` standard, but dart uses the`#9666666`. Maybe the reason that want't add this enhancement.
expect discuss this issue with you.

**Comment by rurico** [comment]
Firstly, Thanks for you nice project, In my current project, used 8 characters to dynamically generate colors. add color depth to express rich colors.
The `HTML` uses the `#66666699` standard, but dart uses the`#9666666`. Maybe the reason that want't add this enhancement.
expect discuss this issue with you.

**Comment by felixblaschke** [comment]
If you like you can implement RGBA parsing (where A is last position in string).
Please use the **nullsafety** branch for the PR because I want to avoid double maintainance.
I don't think we need to add an example because the 8 char parsing isn't a common use case and I don't want to pollute the example page with all possible things :-) It might confuse new users.

I created an issue for that https://github.com/felixblaschke/supercharged/issues/25

**Pull request closed without merging**
